{
'id': 'bugs.core_0870',
'qmid': 'bugs.core_870',
'tracker_id': 'CORE-870',
'title': 'Engine crashes while trying to backup a logically corrupt db',
'description': "This test works only for fb 2.1-2.5 and was converted to dummy one for 3.0 as it needs specificaly corrupted database. We don't have such database with ODS 12 required by fb 3.0+",
'min_versions': '',
'versions': [
{
 'firebird_version': '2.1',
 'platform': 'All',
 'database': 'Existing',
 'database_name': 'core870.fdb',
 'test_type': 'Python',
 'test_script': """import os

print ('Starting backup...')
fbk = os.path.join(context['temp_directory'],'backup.fbk')
runProgram('gbak',['-b','-user',user_name,'-password',user_password,dsn,fbk])
print ('gbak finished...')
if os.path.isfile(fbk):
    print ('Delete backup file...')
    os.remove(fbk)
    print ('Backup file deleted.')
""",
 'expected_stdout': """Starting backup...
gbak finished...
Delete backup file...
Backup file deleted.
"""
},
{
 'firebird_version': '3.0',
 'platform': 'All',
 'page_size': '4096',
 'test_type': 'ISQL',
 'test_script': ''
}
]
}
